### ISSUE TITLE
A user who refreshes the 'logout' page receives an Unauthorized exception

### ISSUE THREAD

**Issue by llayman** [uncw-hfcs/ids-simulator#78]
If a user for some reason needs to go back to the logout page, they are greeted with an unauthorized exception, so they have no way to retrieve their completion code.

You could deal with this either byremoving the authorization constraint from logout, and passing their completion code to the logout page as a parameter when they successfully complete the post questionnaire, or

**Comment by llayman** [comment]
I got the code, but then received the follow exception when I refreshed the page.

```
Traceback (most recent call last):
  File "/home/lucas/git/ids-simulator/.venv/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/lucas/git/ids-simulator/.venv/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/lucas/git/ids-simulator/.venv/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lucas/git/ids-simulator/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lucas/git/ids-simulator/.venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lucas/git/ids-simulator/.venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lucas/git/ids-simulator/.venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lucas/git/ids-simulator/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lucas/git/ids-simulator/.venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lucas/git/ids-simulator/.venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lucas/git/ids-simulator/crywolf/crywolf.py", line 252, in logout
    code = current_user.completion_code
  File "/home/lucas/git/ids-simulator/.venv/lib/python3.6/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'completion_code'
```
